import Head from "next/head";
import Image from "next/image";
import styles from "../styles/home.module.scss";
import MenuListComposition from "../Components/HomePage/CitiesDropDown";
import CitiesList from "../Components/HomePage/CitiesList";
import Footer from "../Components/Footer/Footer";
import NameStyle from "../Components/testcomponent/NameStyle";
import SearchBar from "../Components/SearchBar/SearchBar";
import Card from "../Components/Card/Card";
// import {HomePage} from ""'../public'
// import { newRoom } from "../backEnd/controllers/roomControllers.ts";

export default function Home() {
  // console.log(newRoom());
  return (
    <div>
      <Head>
        <title>OYO Rooms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <MenuListComposition {...list}></MenuListComposition> */}
        <div className={styles.cities}>
          <CitiesList />
        </div>
        <div className={styles.searchBar}>
          <SearchBar />
        </div>
        <Card />
      </main>

      {/* <footer className={styles.footer}> */}
      {/* <Footer /> */}
    </div>
  );
}
