import React from "react";

import Head from "next/head";
import Image from "next/image";
import Footer from "../Footer/Footer";
import Card from "../Card/Card";
import CitiesList from "./CitiesList";
import styles from "../../styles/home.module.scss";
import SearchBar from "../SearchBar/SearchBar";

import { useSelector } from "react-redux";
export default function HomePage() {
  const { rooms } = useSelector((state) => state.allRooms);
  console.log(rooms);

  return (
    <>
      <Head>
        <title>OYO Rooms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.cities} style={{zIndex:1000}}>
          <CitiesList />
        </div>
        <div className={styles.searchBar} >
          <SearchBar />
        </div>
        {/* <div style={{zIndex:1000,margin:"10%"}}>
        <picture className={styles.banner}>
          <source srcSet="../../public/offerBanner.webp" type="image/webp" />
          <img src="https://assets.oyoroomscdn.com/cmsMedia/7700e1f2-3d24-41e8-8c71-f4336c625a88.jpg" alt="OYO" />
        </picture>
        </div> */}
        <Card />
      </main>
      {/* <footer className={styles.footer}>
            <Footer />
        </footer> */}
    </>
  );
}
